### ISSUE TITLE
Pytorch gpgpusim is not entering kernels

### ISSUE THREAD

**Issue by jin8495** [gpgpu-sim/gpgpu-sim_distribution#195]
My env:
Docker container
Ubuntu 16.04
CUDA 8.0 / cudnn 7
python 3.5
gpgpu-sim 4.0.0

I am having a trouble with pytorch-gpgpusim.

I could build pytorch 0.4.1 and gpgpu-sim succesfully thanks to https://docs.google.com/document/d/17fSM2vrWodP8rWR7ctpgaggVXEw0uD2VCAh0Gi4Gpb4/edit.

And I also checked running on this toy code below.

`import torch

a = torch.randn(5,5)
b = torch.randn(5,5)
c = torch.matmul(a,b)`

But MNIST Example from the google docs, I keep having segmentation fault.
From gdb, I could find where it encounters seg fault, but I don't know what to do with this.

![image](https://user-images.githubusercontent.com/49510451/87841478-6e7aea00-c8e0-11ea-91e4-3fe0280dfb00.png)

**Comment by jin8495** [comment]
I found what went wrong!
I just downloaded docker image file from docker hub to save some times.
Even though the provider was NVIDIA, the image had cudnn 7.2.1 which is not compatible with cuda8.0. So I downgraded to cudnn 7.1.4.
And it worked!

**Comment by jin8495** [comment]
I thought I fixed issues but I found that pytorch-gpgpusim is not working properly.
It can extract and load PTXs but it cannot enter CUDA kernels.

Below image is a simple matmul kernel that I wrote(Not from any libraries). As you see it is setting up arguments and entering kernel showing 'cudaLaunch' after loading PTX.
![image](https://user-images.githubusercontent.com/49510451/88122425-8bc2f780-cc03-11ea-825a-e8727a88216f.png)

And this is pytorch matmul program. It is not entering kernel after a really long PTX loading. Just showing results like below.
![image](https://user-images.githubusercontent.com/49510451/88127673-3c82c400-cc0f-11ea-8da3-2f447842e29d.png)

It looks like skipping gpgpu-sim and just calculated like that. So I changed my code 
```
import torch

if(torch.cuda.is_available()):
    a = torch.randn(5,5)
    b = torch.randn(5,5)
    a.cuda()
    b.cuda()

    c = torch.matmul(a,b)
```

As you see below, now it doesn't seem like it is skipping GPGPU-sim but still not entering the kernels.
![image](https://user-images.githubusercontent.com/49510451/88127833-97b4b680-cc0f-11ea-8d10-41e0499d731d.png)

**Comment by cng123** [comment]
Hi,

It seems like the script you are running does not launch any kernels (I know it might be misleading since the GPGPU-Sim splash was printed and the PTX was parsed, but that occurs at `import torch` as opposed to when the first kernel is launched).  To verify this, you could run your script with NVProf or NV-Nsight. This is what I got with your script:
![image](https://user-images.githubusercontent.com/21072486/88134021-6351e380-cb98-11ea-9f31-1d8df133a78f.png)
this means that `c = torch.matmul(a, b)` was actually ran on the CPU instead, since no kernels were detected.

I think for `torch.matmul` to run on the GPU, the following code snippet does the trick:
```import torch
if (torch.cuda.is_available()):
    cuda = torch.device('cuda')
    a = torch.randn(5,5).to(device=cuda)
    b = torch.randn(5,5).to(device=cuda)
    c = torch.matmul(a, b)
```
Under NV-NSight, launched kernels are detected:
![image](https://user-images.githubusercontent.com/21072486/88134545-bed0a100-cb99-11ea-8997-57413339683c.png)

Hopefully this helps!

**Comment by jin8495** [comment]
@cng123 
Thank you!! It worked :)
