### ISSUE TITLE
’ERROR: Attribute number 20 unimplemented‘ with WSL2+cuda(10/11)+gpgpu-sim

### ISSUE THREAD

**Issue by ymlei** [gpgpu-sim/gpgpu-sim_distribution#206]
I tried WSL2 with gpgpu-sim. This error occurs with cuda11.1/11.0/10.2. After all building and compiling, libcudart.so are linked to the execution file and config files are copied to the execution file's path. When running cuda sample matrixmul (and many other samples), an error ’ERROR: Attribute number 20 unimplemented‘ occurred. Does anyone know how to fix it? Does anyone succeed with gpgpu-sim in WSL?
![image](https://user-images.githubusercontent.com/33507651/97086770-f860ee80-1657-11eb-8028-4549208ba514.png)

**Comment by mattsinc** [comment]
The error is printing out here: https://github.com/gpgpu-sim/gpgpu-sim_distribution/blob/5e8e84976b63186ce4682e3dbb1bea84542558a9/libcuda/cuda_runtime_api.cc#L1855

Looking at cudaDeviceGetAttribute, which is the function that line is in, it appears that case 20 is not implemented.  So you'd need to add it.  Looking at cudaDeviceGetAttribute (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1gg49e2f8c2c0bd6fe264f2fc970912e5cde05045d1eba85ad27f416222c2d03ace), it appears the 20th option is cudaDevAttrComputeMode, so that's what you'd need to add.  You may also consider checking the get_prop() function to see if it implements this information already (although I don't think it does).

Hope this helps,
Matt

**Comment by ymlei** [comment]
@mattsinc Thanks for your quick reply!
According to the CUDA document, the 20th option, cudaDevAttrComputeMode, has 4 modes (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g7eb25f5413a962faad0956d92bae10d0)
I'm a newer to gpgpu-sim. What information should I based on to add 20th's implement and get_prop() (it has not implemented prop for computeMode)?
In my opinion, cudaDeviceGetAttribute is called by CUDA API findCudaDevice() and aims to get device information. Is that correct? Should I implement based on device information in gpgpu-sim.config?

**Comment by ymlei** [comment]
Attribute number 20 unimplemented error can be fixed by removing functions "findCudaDevice()" and "cudaGetDeviceProperties()" in cuda samples source codes.
gpgpu-sim doesn't support the above functions completely.
A more essential solution is implementing them in gpgpu-sim. Provided by @mattsinc. Thank you!
